// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCvAqSYulN9cWMAKJr7KtNNHT523JFgpU',
    appId: '1:375201582761:android:06b81113bf8718ae2063b8',
    messagingSenderId: '375201582761',
    projectId: 'echo-1eb4d',
    storageBucket: 'echo-1eb4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ebIJt6OP-iO2DTlbMCEf-pA7Hae_NkQ',
    appId: '1:375201582761:ios:00865a86ba21b91c2063b8',
    messagingSenderId: '375201582761',
    projectId: 'echo-1eb4d',
    storageBucket: 'echo-1eb4d.firebasestorage.app',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ebIJt6OP-iO2DTlbMCEf-pA7Hae_NkQ',
    appId: '1:375201582761:ios:00865a86ba21b91c2063b8',
    messagingSenderId: '375201582761',
    projectId: 'echo-1eb4d',
    storageBucket: 'echo-1eb4d.firebasestorage.app',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCngLdXt1itEF-cbiNU9J2iU8HudoEe_yM',
    appId: '1:375201582761:web:6d0dd4ce9900d0092063b8',
    messagingSenderId: '375201582761',
    projectId: 'echo-1eb4d',
    authDomain: 'echo-1eb4d.firebaseapp.com',
    storageBucket: 'echo-1eb4d.firebasestorage.app',
    measurementId: 'G-FGHC7L4TJQ',
  );
}
